name: lotto_world_pro
description: A Lotto app with tips and statistics

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  intl: ^0.18.1
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
#   # intl: ^0.18.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/lotto_ball_icon.png"
